<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ELSA" failures="1" tests="3" name="TestOnDevice2" time="89.724" errors="0" timestamp="2025-06-18T16:28:56 EDT">
  <testcase classname="org.testCase.TestCase1" name="FirstCase" time="8.355">
    <failure type="java.lang.AssertionError" message="expected [Please enter your name2] but found [Please enter your name]">
      <![CDATA[java.lang.AssertionError: expected [Please enter your name2] but found [Please enter your name]
at org.testCase.TestCase1.FirstCase(TestCase1.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- FirstCase -->
  <testcase classname="org.testCase.TestCase2" name="SecondCase" time="15.223"/>
  <testcase classname="org.testCase.TestCase3" name="ThirdCase" time="19.238"/>
</testsuite> <!-- TestOnDevice2 -->
